<a href="https://colab.research.google.com/github/HARRY-hussein/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

In [ ]:
import pandas as pd

In [ ]:
print([pd.__version__])

['2.2.2']

In [ ]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Bugatti", "Ferarri", "Nissan", "Porsche"],
  'counts': [3, 7, 2, 4, 3, 5, 6]
}


df = pd.DataFrame(mydataset)

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6

In [ ]:
df.head(7) # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6

In [ ]:
df.tail() # oxiridan boshlab 5 rows sanaydi

      cars  counts
2     Ford       2
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6

In [ ]:
df.shape

(7, 2)

In [ ]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.dtypes

cars      object
counts     int64
dtype: object

In [ ]:
df.describe() # numerical columns only

         counts
count  7.000000
mean   4.285714
std    1.799471
min    2.000000
25%    3.000000
50%    4.000000
75%    5.500000
max    7.000000

In [ ]:
df.describe(include="all")

       cars    counts
count     7  7.000000
unique    7       NaN
top     BMW       NaN
freq      1       NaN
mean    NaN  4.285714
std     NaN  1.799471
min     NaN  2.000000
25%     NaN  3.000000
50%     NaN  4.000000
75%     NaN  5.500000
max     NaN  7.000000

In [ ]:
df.iloc[2:4] # 2 qatordan 4 qatorgacha bo'lgan indexlarni olib keladi. [3:] = 3-qatordan boshlab oxirigacha bo'lgan indexni oladi!

      cars  counts
2     Ford       2
3  Bugatti       4

In [ ]:
df.loc[:, "cars"]

0        BMW
1      Volvo
2       Ford
3    Bugatti
4    Ferarri
5     Nissan
6    Porsche
Name: cars, dtype: object

In [ ]:
df['counts'] > 4

0    False
1     True
2    False
3    False
4    False
5     True
6     True
Name: counts, dtype: bool

In [ ]:
df[df['counts'] > 4] # bu holatda boolean qaytarmasdan faqat 4 dan katta bo'lganlarni oladi!

      cars  counts
1    Volvo       7
5   Nissan       5
6  Porsche       6

In [ ]:
df.mean(numeric_only=True)
# df['counts'].mean() # mana bu holatda ham ishlatish mumkin!

counts    4.285714
dtype: float64

In [ ]:
df.sum() # yeg'indini chiqaradi!

cars      BMWVolvoFordBugattiFerarriNissanPorsche
counts                                         30
dtype: object

In [ ]:
df.min()

cars      BMW
counts      2
dtype: object

In [ ]:
df.max()

cars      Volvo
counts        7
dtype: object

In [ ]:
df.median(numeric_only=True)

counts    4.0
dtype: float64

In [ ]:
df.count()

cars      7
counts    7
dtype: int64

In [ ]:
df.std(numeric_only=True)

counts    1.799471
dtype: float64

In [ ]:
data_with_missing ={
    "cars": ["BMW", "Volvo", None, "Bugatti", "Ferarri", None, "Porsche"],
    "counts": [None, 7, 5, 4, 3, None, 9]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     NaN
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5     None     NaN
6  Porsche     9.0

In [ ]:
df_missing.isnull()

    cars  counts
0  False    True
1  False   False
2   True   False
3  False   False
4  False   False
5   True   False
6  False    True

In [ ]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [ ]:
df_missing.dropna()

      cars  counts
1    Volvo     7.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [ ]:
df_missing.dropna(how="all")

      cars  counts
0      BMW     NaN
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [ ]:
df_missing.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [ ]:
df_missing.dropna(subset=["counts"]) # faqat counts columns ni tekshiradi!

      cars  counts
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [ ]:
df_missing.fillna(0) # None qatorlarga data joylaydi

      cars  counts
0      BMW     0.0
1    Volvo     7.0
2        0     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5        0     0.0
6  Porsche     9.0

In [ ]:
df_missing.fillna({"cars": "unknow", "counts": 0}) # None qatorlarga data joylaydi

      cars  counts
0      BMW     0.0
1    Volvo     7.0
2   unknow     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5   unknow     0.0
6  Porsche     9.0

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# df = pd.read_csv("Titanic-Dataset.csv")

df = pd.read_excel("Titanic-Dataset.xlsx")
df.tail()

# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.to_excel("test.xlsx")

In [ ]:
# Series => 1D
cars = pd.Series(["BMW", "Volvo", "Ford", "Bugatti", "Ferarri", "Nissan", "Porsche"])
print(cars)

0        BMW
1      Volvo
2       Ford
3    Bugatti
4    Ferarri
5     Nissan
6    Porsche
dtype: object

In [ ]:
cars_serise = data_with_missing["cars"]
print(cars_serise)

['BMW', 'Volvo', None, 'Bugatti', 'Ferarri', None, 'Porsche']